name: Auto Presence

on:
  schedule:
    - cron: '0 7 * * *'   # 09h Paris (UTC+2 = 7h UTC)
    - cron: '0 12 * * *'  # 14h Paris (UTC+2 = 12h UTC)
  workflow_dispatch: {}   # permet de lancer manuellement

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run script
        run: python main.py
